agents:
  queue: "aws"

env:
  TERM: "xterm"

steps:
  - label: ":angular: Build the application"
    key: "install"
    command: | 
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "--- Install NPM dependencies"
      npm install

  - wait  

  - label: ":jasmine: Unit tests run"
    depends_on: 'install'
    command: |
      echo "Running unit tests"
      npm run test:ci
    - wait: ~
    continue_on_failure: true

  - label: ":cypress: Cypress"
    depends_on: 'install'
    command: |
      # if necessary, reinstall "correct" version of Cypress
      # a common situation if testing preview binary build
      # "$(npm bin)/cypress" install --force

      echo "+++ Run Cypress tests"

      npm run cy:ci

      buildkite-agent artifact upload "/var/lib/buildkite-agent/builds/AWSLXINTBTP01-weforum-local-2/world-economic-forum/kb-tes/cypress/screenshots//**/*.jpg;*/**/*.jpeg;*/**/*.png"
    
    artifact_paths:
      - "/var/lib/buildkite-agent/builds/AWSLXINTBTP01-weforum-local-2/world-economic-forum/kb-tes/cypress/screenshots/"