env:
  TERM: "xterm"

steps:
  - label: ":cypress: Cypress"
    command: |
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "--- RUN all"
      npm install npm-run-all
      
      echo "--- Install NPM dependencies"
      npm install
    

      # if necessary, reinstall "correct" version of Cypress
      # a common situation if testing preview binary build
      # "$(npm bin)/cypress" install --force

      echo "+++ Run Cypress tests"
      npm run cy:ci