env:
  TERM: "xterm"

steps:
  - label: ":angular: Build the application"
    command: | 
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "--- Install NPM dependencies"
      npm install

    key: "build"
    plugins: 
      - cache#v0.6.0:
          manifest: package-lock.json
          path: node_modules
          restore: file
          save: file 
    
  - label: ":jasmine: Unit tests run"
    command: |
      echo "Running unit tests"

      npm run test:ci
    depends_on: 'build'
    plugins: 
      - cache#v0.6.0:
          manifest: package-lock.json
          path: node_modules
          restore: file
  
  - wait: ~
    continue_on_failure: true
  - label: ":cypress: Cypress"
    depends_on: 'build'
    command: |
      # if necessary, reinstall "correct" version of Cypres
      # a common situation if testing preview binary build
      # "$(npm bin)/cypress" install --force

      echo "+++ Run Cypress tests"

      npm run cy:ci

      buildkite-agent artifact upload "/var/lib/buildkite-agent/builds/AWSLXINTBTP01-weforum-local-2/world-economic-forum/kb-tes/cypress/screenshots//**/*.jpg;*/**/*.jpeg;*/**/*.png"
    
    artifact_paths:
      - "/var/lib/buildkite-agent/builds/AWSLXINTBTP01-weforum-local-2/world-economic-forum/kb-tes/cypress/screenshots/"