agents:
  queue: "aws"

env:
  TERM: "xterm"

steps:
  - label: ":cypress: Cypress"
    command: |
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "--- Install NPM dependencies"
      npm install
    

      # if necessary, reinstall "correct" version of Cypress
      # a common situation if testing preview binary build
      # "$(npm bin)/cypress" install --force

      echo "+++ Run Cypress tests"
      echo pwd
      npm run cy:ci
      buildkite-agent artifact upload "cypress/**/*.jpg;*/**/*.jpeg;*/**/*.png"
    artifact_paths:
      - "/var/lib/buildkite-agent/builds/AWSLXINTBTP01-weforum-local-5/world-economic-forum/kb-test/cypress/screenshots/**/*"